### PR TITLE
Adding stuff for chapter 5 of AiA book

### PR DESCRIPTION
**Pull request by LightGuard**
Trying a few things, some don't need to be there any longer, but I think I'd keep it for future tests.

### CODE REVIEW

**Comment by lordofthejars** [comment]
For what I understand we will need to update the example with JSF too so we can write a simple Drone example, or you prefer to avoid JSF and be aligned with AngularJS

**Comment by LightGuard** [comment]
You mean for warp?

On Wednesday, July 29, 2015, Alex Soto notifications@github.com wrote:

> For what I understand we will need to update the example with JSF too so
> we can write a simple Drone example, or you prefer to avoid JSF and be
> aligned with AngularJS
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lordofthejars/todos/pull/1#issuecomment-126015751.

## 

Sent from Gmail Mobile

**Comment by lordofthejars** [comment]
Well for Warp but also for simple Drone example.

**Comment by LightGuard** [comment]
Don't need JSF for drone. Dine is just the selenium part

On Thursday, July 30, 2015, Alex Soto notifications@github.com wrote:

> Well for Warp but also for simple Drone example.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lordofthejars/todos/pull/1#issuecomment-126231888.

## 

Sent from Gmail Mobile

**Comment by lordofthejars** [comment]
yes I know I was only thinking for simple use case or to show someone who wants to use jsf, well anyway I am going to try to implement jsf too in this example.

**Pull request merged**
